/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

/**
 *
 * @author Usuario
 */
public class EjemplosMenus extends javax.swing.JFrame {

    /**
     * Creates new form EjemplosMenus
     */
    public EjemplosMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeleccion = new javax.swing.JTextField();
        mnPrincipal = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnArchivoAbrir = new javax.swing.JMenuItem();
        mnArchivoGuardar = new javax.swing.JMenuItem();
        mnArchivoCerrar = new javax.swing.JMenuItem();
        mnOpciones = new javax.swing.JMenu();
        mnOpcionesPdf = new javax.swing.JMenuItem();
        mnOpcionesDocx = new javax.swing.JMenuItem();
        spArchivo = new javax.swing.JPopupMenu.Separator();
        mnArchivoSalir = new javax.swing.JMenuItem();
        mnEdicion = new javax.swing.JMenu();
        mnEdicionCopiar = new javax.swing.JMenuItem();
        mnEdicionCortar = new javax.swing.JMenuItem();
        mnEdicionPegar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSeleccion.setColumns(25);

        mnArchivo.setText("Archivo");

        mnArchivoAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnArchivoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/open.png"))); // NOI18N
        mnArchivoAbrir.setText("Abrir");
        mnArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArchivoAbrirActionPerformed(evt);
            }
        });
        mnArchivo.add(mnArchivoAbrir);

        mnArchivoGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnArchivoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Save.png"))); // NOI18N
        mnArchivoGuardar.setText("Guardar");
        mnArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArchivoGuardarActionPerformed(evt);
            }
        });
        mnArchivo.add(mnArchivoGuardar);

        mnArchivoCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnArchivoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Close.png"))); // NOI18N
        mnArchivoCerrar.setText("Cerrar");
        mnArchivoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArchivoCerrarActionPerformed(evt);
            }
        });
        mnArchivo.add(mnArchivoCerrar);

        mnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Options.png"))); // NOI18N
        mnOpciones.setText("Opciones");

        mnOpcionesPdf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpcionesPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/PDF.png"))); // NOI18N
        mnOpcionesPdf.setText("Guardar a PDF");
        mnOpcionesPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcionesPdfActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpcionesPdf);

        mnOpcionesDocx.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpcionesDocx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/DOCX.png"))); // NOI18N
        mnOpcionesDocx.setText("Guardar a DOCX");
        mnOpcionesDocx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcionesDocxActionPerformed(evt);
            }
        });
        mnOpciones.add(mnOpcionesDocx);

        mnArchivo.add(mnOpciones);
        mnArchivo.add(spArchivo);

        mnArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Exit.png"))); // NOI18N
        mnArchivoSalir.setText("Salir");
        mnArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArchivoSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(mnArchivoSalir);

        mnPrincipal.add(mnArchivo);

        mnEdicion.setText("Edición");

        mnEdicionCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnEdicionCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Copy.png"))); // NOI18N
        mnEdicionCopiar.setText("Copiar");
        mnEdicionCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEdicionCopiarActionPerformed(evt);
            }
        });
        mnEdicion.add(mnEdicionCopiar);

        mnEdicionCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnEdicionCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Cut.png"))); // NOI18N
        mnEdicionCortar.setText("Cortar");
        mnEdicionCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEdicionCortarActionPerformed(evt);
            }
        });
        mnEdicion.add(mnEdicionCortar);

        mnEdicionPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnEdicionPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Paste.png"))); // NOI18N
        mnEdicionPegar.setText("Pegar");
        mnEdicionPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEdicionPegarActionPerformed(evt);
            }
        });
        mnEdicion.add(mnEdicionPegar);

        mnPrincipal.add(mnEdicion);

        setJMenuBar(mnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(txtSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArchivoAbrirActionPerformed
        txtSeleccion.setText("Archivo -> Abrir");
    }//GEN-LAST:event_mnArchivoAbrirActionPerformed

    private void mnArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArchivoGuardarActionPerformed
       txtSeleccion.setText("Archivo -> Guardar");
    }//GEN-LAST:event_mnArchivoGuardarActionPerformed

    private void mnArchivoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArchivoCerrarActionPerformed
        txtSeleccion.setText("Archivo -> Cerrar");
    }//GEN-LAST:event_mnArchivoCerrarActionPerformed

    private void mnOpcionesPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcionesPdfActionPerformed
        txtSeleccion.setText("Archivo -> Opciones -> Guardar a PDF");
    }//GEN-LAST:event_mnOpcionesPdfActionPerformed

    private void mnOpcionesDocxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcionesDocxActionPerformed
       txtSeleccion.setText("Archivo -> Opciones -> Guardar a DOCX");
    }//GEN-LAST:event_mnOpcionesDocxActionPerformed

    private void mnArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArchivoSalirActionPerformed
        txtSeleccion.setText("Archivo -> Salir");
    }//GEN-LAST:event_mnArchivoSalirActionPerformed

    private void mnEdicionCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEdicionCopiarActionPerformed
       txtSeleccion.setText("Edicion -> Copiar");
    }//GEN-LAST:event_mnEdicionCopiarActionPerformed

    private void mnEdicionCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEdicionCortarActionPerformed
       txtSeleccion.setText("Edicion -> Cortar");
    }//GEN-LAST:event_mnEdicionCortarActionPerformed

    private void mnEdicionPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEdicionPegarActionPerformed
        txtSeleccion.setText("Edicion -> Pegar");
    }//GEN-LAST:event_mnEdicionPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemplosMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemplosMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemplosMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemplosMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemplosMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenuItem mnArchivoAbrir;
    private javax.swing.JMenuItem mnArchivoCerrar;
    private javax.swing.JMenuItem mnArchivoGuardar;
    private javax.swing.JMenuItem mnArchivoSalir;
    private javax.swing.JMenu mnEdicion;
    private javax.swing.JMenuItem mnEdicionCopiar;
    private javax.swing.JMenuItem mnEdicionCortar;
    private javax.swing.JMenuItem mnEdicionPegar;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnOpcionesDocx;
    private javax.swing.JMenuItem mnOpcionesPdf;
    private javax.swing.JMenuBar mnPrincipal;
    private javax.swing.JPopupMenu.Separator spArchivo;
    private javax.swing.JTextField txtSeleccion;
    // End of variables declaration//GEN-END:variables
}
